// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculatorpb/calculator.proto

package calculatorpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SumRequest struct {
	FirstNum             int32    `protobuf:"varint,1,opt,name=first_num,json=firstNum,proto3" json:"first_num,omitempty"`
	SecondNum            int32    `protobuf:"varint,2,opt,name=second_num,json=secondNum,proto3" json:"second_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumRequest) Reset()         { *m = SumRequest{} }
func (m *SumRequest) String() string { return proto.CompactTextString(m) }
func (*SumRequest) ProtoMessage()    {}
func (*SumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{0}
}

func (m *SumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumRequest.Unmarshal(m, b)
}
func (m *SumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumRequest.Marshal(b, m, deterministic)
}
func (m *SumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumRequest.Merge(m, src)
}
func (m *SumRequest) XXX_Size() int {
	return xxx_messageInfo_SumRequest.Size(m)
}
func (m *SumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SumRequest proto.InternalMessageInfo

func (m *SumRequest) GetFirstNum() int32 {
	if m != nil {
		return m.FirstNum
	}
	return 0
}

func (m *SumRequest) GetSecondNum() int32 {
	if m != nil {
		return m.SecondNum
	}
	return 0
}

type SumResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SumResponse) Reset()         { *m = SumResponse{} }
func (m *SumResponse) String() string { return proto.CompactTextString(m) }
func (*SumResponse) ProtoMessage()    {}
func (*SumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{1}
}

func (m *SumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SumResponse.Unmarshal(m, b)
}
func (m *SumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SumResponse.Marshal(b, m, deterministic)
}
func (m *SumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SumResponse.Merge(m, src)
}
func (m *SumResponse) XXX_Size() int {
	return xxx_messageInfo_SumResponse.Size(m)
}
func (m *SumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SumResponse proto.InternalMessageInfo

func (m *SumResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type PrimeDecompRequest struct {
	NumForPrimedecomp    int32    `protobuf:"varint,1,opt,name=num_for_primedecomp,json=numForPrimedecomp,proto3" json:"num_for_primedecomp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeDecompRequest) Reset()         { *m = PrimeDecompRequest{} }
func (m *PrimeDecompRequest) String() string { return proto.CompactTextString(m) }
func (*PrimeDecompRequest) ProtoMessage()    {}
func (*PrimeDecompRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{2}
}

func (m *PrimeDecompRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeDecompRequest.Unmarshal(m, b)
}
func (m *PrimeDecompRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeDecompRequest.Marshal(b, m, deterministic)
}
func (m *PrimeDecompRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeDecompRequest.Merge(m, src)
}
func (m *PrimeDecompRequest) XXX_Size() int {
	return xxx_messageInfo_PrimeDecompRequest.Size(m)
}
func (m *PrimeDecompRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeDecompRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeDecompRequest proto.InternalMessageInfo

func (m *PrimeDecompRequest) GetNumForPrimedecomp() int32 {
	if m != nil {
		return m.NumForPrimedecomp
	}
	return 0
}

type PrimeDecompResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrimeDecompResponse) Reset()         { *m = PrimeDecompResponse{} }
func (m *PrimeDecompResponse) String() string { return proto.CompactTextString(m) }
func (*PrimeDecompResponse) ProtoMessage()    {}
func (*PrimeDecompResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_87e717c78a24322a, []int{3}
}

func (m *PrimeDecompResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimeDecompResponse.Unmarshal(m, b)
}
func (m *PrimeDecompResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimeDecompResponse.Marshal(b, m, deterministic)
}
func (m *PrimeDecompResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimeDecompResponse.Merge(m, src)
}
func (m *PrimeDecompResponse) XXX_Size() int {
	return xxx_messageInfo_PrimeDecompResponse.Size(m)
}
func (m *PrimeDecompResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimeDecompResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrimeDecompResponse proto.InternalMessageInfo

func (m *PrimeDecompResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*SumRequest)(nil), "calculator.SumRequest")
	proto.RegisterType((*SumResponse)(nil), "calculator.SumResponse")
	proto.RegisterType((*PrimeDecompRequest)(nil), "calculator.PrimeDecompRequest")
	proto.RegisterType((*PrimeDecompResponse)(nil), "calculator.PrimeDecompResponse")
}

func init() { proto.RegisterFile("calculatorpb/calculator.proto", fileDescriptor_87e717c78a24322a) }

var fileDescriptor_87e717c78a24322a = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x5d, 0xc5, 0x62, 0xa7, 0x22, 0x34, 0x85, 0x2a, 0x95, 0xaa, 0x04, 0x04, 0x2f, 0xae,
	0xa2, 0x17, 0xcf, 0x5a, 0xc4, 0x53, 0x29, 0xbb, 0x37, 0x2f, 0x4b, 0x9b, 0x4e, 0x61, 0x61, 0x27,
	0x89, 0x49, 0xc6, 0xff, 0xe3, 0x3f, 0x15, 0xd3, 0xad, 0xbb, 0x52, 0xec, 0x71, 0xde, 0x97, 0xbc,
	0xc7, 0xcc, 0x83, 0xb1, 0x9a, 0x57, 0x8a, 0xab, 0x79, 0x30, 0xce, 0x2e, 0xee, 0x9a, 0x21, 0xb5,
	0xce, 0x04, 0x23, 0xa0, 0x51, 0xe4, 0x1b, 0x40, 0xce, 0x94, 0xe1, 0x07, 0xa3, 0x0f, 0xe2, 0x1c,
	0xba, 0xab, 0xd2, 0xf9, 0x50, 0x68, 0xa6, 0xb3, 0xe4, 0x2a, 0xb9, 0x39, 0xcc, 0x8e, 0xa2, 0x30,
	0x65, 0x12, 0x63, 0x00, 0x8f, 0xca, 0xe8, 0x65, 0xa4, 0xfb, 0x91, 0x76, 0xd7, 0xca, 0x94, 0x49,
	0x5e, 0x43, 0x2f, 0x3a, 0x79, 0x6b, 0xb4, 0x47, 0x31, 0x84, 0x8e, 0x43, 0xcf, 0x55, 0xa8, 0x7d,
	0xea, 0x49, 0x4e, 0x40, 0xcc, 0x5c, 0x49, 0x38, 0x41, 0x65, 0xc8, 0x6e, 0x82, 0x53, 0x18, 0x68,
	0xa6, 0x62, 0x65, 0x5c, 0x61, 0x7f, 0xe8, 0x32, 0xd2, 0xfa, 0x6b, 0x5f, 0x33, 0xbd, 0x1a, 0x37,
	0x6b, 0x80, 0xbc, 0x85, 0xc1, 0x1f, 0x97, 0xdd, 0xa1, 0x0f, 0x5f, 0x09, 0xf4, 0x5f, 0x7e, 0x97,
	0xce, 0xd1, 0x7d, 0x96, 0x0a, 0xc5, 0x13, 0x1c, 0xe4, 0x4c, 0x62, 0x98, 0xb6, 0x2e, 0xd4, 0x1c,
	0x63, 0x74, 0xba, 0xa5, 0xaf, 0x53, 0xe4, 0x9e, 0xc8, 0xa0, 0xd7, 0x8a, 0x17, 0x17, 0xed, 0x97,
	0xdb, 0xdb, 0x8d, 0x2e, 0xff, 0xe5, 0x1b, 0xc7, 0xfb, 0xe4, 0xf9, 0xe4, 0xfd, 0xb8, 0x5d, 0xdb,
	0xa2, 0x13, 0xcb, 0x7a, 0xfc, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc3, 0x0f, 0x97, 0x58, 0xcd, 0x01,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculatorServiceClient is the client API for CalculatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculatorServiceClient interface {
	Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error)
	PrimeDecomp(ctx context.Context, in *PrimeDecompRequest, opts ...grpc.CallOption) (CalculatorService_PrimeDecompClient, error)
}

type calculatorServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculatorServiceClient(cc *grpc.ClientConn) CalculatorServiceClient {
	return &calculatorServiceClient{cc}
}

func (c *calculatorServiceClient) Sum(ctx context.Context, in *SumRequest, opts ...grpc.CallOption) (*SumResponse, error) {
	out := new(SumResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculatorService/Sum", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calculatorServiceClient) PrimeDecomp(ctx context.Context, in *PrimeDecompRequest, opts ...grpc.CallOption) (CalculatorService_PrimeDecompClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CalculatorService_serviceDesc.Streams[0], "/calculator.CalculatorService/PrimeDecomp", opts...)
	if err != nil {
		return nil, err
	}
	x := &calculatorServicePrimeDecompClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CalculatorService_PrimeDecompClient interface {
	Recv() (*PrimeDecompResponse, error)
	grpc.ClientStream
}

type calculatorServicePrimeDecompClient struct {
	grpc.ClientStream
}

func (x *calculatorServicePrimeDecompClient) Recv() (*PrimeDecompResponse, error) {
	m := new(PrimeDecompResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CalculatorServiceServer is the server API for CalculatorService service.
type CalculatorServiceServer interface {
	Sum(context.Context, *SumRequest) (*SumResponse, error)
	PrimeDecomp(*PrimeDecompRequest, CalculatorService_PrimeDecompServer) error
}

func RegisterCalculatorServiceServer(s *grpc.Server, srv CalculatorServiceServer) {
	s.RegisterService(&_CalculatorService_serviceDesc, srv)
}

func _CalculatorService_Sum_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculatorServiceServer).Sum(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculatorService/Sum",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculatorServiceServer).Sum(ctx, req.(*SumRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalculatorService_PrimeDecomp_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PrimeDecompRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CalculatorServiceServer).PrimeDecomp(m, &calculatorServicePrimeDecompServer{stream})
}

type CalculatorService_PrimeDecompServer interface {
	Send(*PrimeDecompResponse) error
	grpc.ServerStream
}

type calculatorServicePrimeDecompServer struct {
	grpc.ServerStream
}

func (x *calculatorServicePrimeDecompServer) Send(m *PrimeDecompResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _CalculatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculatorService",
	HandlerType: (*CalculatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sum",
			Handler:    _CalculatorService_Sum_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PrimeDecomp",
			Handler:       _CalculatorService_PrimeDecomp_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "calculatorpb/calculator.proto",
}
